kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  annotations:
    ibm.io/provisioning-status: inprogress
  name: {{ .Release.Name }}-pvc-oracle
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: {{ .Values.storage.storageClassName }}
  volumeMode: Filesystem
