kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-role-scc-admin
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["{{ .Release.Namespace }}-{{ .Release.Name }}-scc-admin"]
    verbs: ["use"]
