kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-scc-admin-role-binding
subjects:
  - kind: ServiceAccount
    name:  {{ .Release.Name }}-oracledb-sa
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role-scc-admin
  apiGroup: rbac.authorization.k8s.io