apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oracledb-host
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 1521
      targetPort: 1521
      protocol: TCP
      name: oracle-port

    - port: 2484
      targetPort: 2484
      protocol: TCP
      name: oracle-port-ssl
  selector:
    app: {{ .Release.Name }}-oracledb
